### ISSUE TITLE
How do you know when to refresh the token?

### ISSUE THREAD

**Issue by reivilibre** [danieleades/monzo-lib#26]
The endpoint that acquires access tokens returns an expiry time, but the `refresh_auth` function doesn't expose that and I don't know how you'd know when to refresh — it doesn't look like it happens automatically, for example.

I guess one could detect requests failing with authorisation issues, but that seems like it would be a bit messy?

**Comment by danieleades** [comment]
i think that managing knowing when to refresh is really a slightly higher-level concern than where this library sits.

I have another project with an 'auto-refreshing' client, perhaps i can add that as an example of how this can work

**Comment by danieleades** [comment]
I've merged the example. Will close this issue. Feel free to reopen if this doesn't solve your problem, or you have more questions
